//#ENJOY BRO😍
const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "";
global.video = "";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "Kermd237@gmail.com";
global.location = "Douala, Cameroun";
global.mongodb = process.env.MONGODB_URI || "";
global.allowJids = process.env.ALLOW_JID || "null";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Africa/Douala";
global.github = process.env.GITHUB || "https://github.com/Kgtech-cmr/KERM_MD-V2";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029Vafn6hc7DAX3fzsKtn45";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029Vafn6hc7DAX3fzsKtn45";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/40ffc2a288542560c887c.jpg";
global.devs = "https://wa.me/237650564445 , https://wa.me/237656520674";
global.sudo = process.env.SUDO || "237659262653";
global.owner = process.env.OWNER_NUMBER || "237659262653";
global.style = process.env.STYLE || "3";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "false";
global.userImages = process.env.USER_IMAGES || "https://telegra.ph/file/40ffc2a288542560c887c.jpg";
global.waPresence = process.env.WAPRESENCE || "available";
global.readcmds = process.env.READ_COMMAND || "true";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "false";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://kerm-session-39mi.onrender.com/wasiqr";

global.SESSION_ID =eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkkvQkV0cVI0bHpVZ2Jmc01PSHNKVUMzL00zbjhydzJxWGpyc3NXblBrRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUnYyN3NuYjQrcFBIUlNkSnFDTUhsWGhTOUlKNGhuWVlmeWc4RFlOa21Cdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDTG1SQTB3QWpic2c1bzF1TmFJcDZYZXVsSytKay9pNjVZSzMxd0JwT1dJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvZDA4cU5zeTFMdWREMURPNHpBdW54WlFvUmtkampNajFORFpTend1R2hvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9LZFcyVDR5QjRUNUtBT0VwY0xIOUJnVXU3ZFdHNlI5WWF4bjdVY2VUbU09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9ENUhJUjNLaUhQbVlObUNKOUpDZXFRaSsrRmhBU01yeTRUY3MybXUxMVE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0xiVUlMMkMvbGF2a1NPTlF6c21qTFBWcU9peElQcDJoa3dlcUNkbnUwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSlRPeEtabTFwNzJaazBUd0ZPRytzY1N4Vyt1OThxM2FqNDJLekVHSkYwYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjgzTmFkTThyZDdNMDZNWjlTMEdveDF2eG5tQ3hjZG55V1MyK2pTNlZhMGp3c1k5eGhINklCUlUwNDZubkJqSHZKRkNOUlFPWkRTMnF4WW5JRzdCSGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MSwiYWR2U2VjcmV0S2V5IjoiaWtuajZiT0k4YTlqUldiWjYwNUdob0xSVEhSV3I4d0MxWlhrS1NNQlVvOD0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMkhoWlVIQ2xTb20yamxxejBhUWNJUSIsInBob25lSWQiOiI4MThkZjNjZS04MDMzLTRjNzgtOTZiYi1mOWMwZWM2YWRlNjciLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiajNzeXNaT01DS2E3b2YveXNGK3lnaWkyOUlVPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IiswcVdmMXhNU3Vxd0lCbFZ3M3EwZ1dqTzJMQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJQOEJSRTFFWCIsIm1lIjp7ImlkIjoiMjM3NjU5MjYyNjUzOjFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2QgfCdkKXwnZCA8J2QgvCdkIog8J2QivCdkIjwnZCN8J2QhiDwnZCL8J2QhPCdkI7wnZCN8J2QiPCdkIPwnZCA8J2QkiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUFhxeFU4UTUrcnV0UVlZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQUVZYks4K1grVDJqQkdKazVHcFJKOHRMTmRhWWtwVG1pRDEwN0NNWUxFUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoibkxpVFFaeHc0ajJIODc0K0VLdFlDOFgxS1Uzd1dDQWQ3V3hBNm05ZjY5emxnZE1HeUtyMWdmZ3dvaGZMUkFXV2pTVmhsM05Rd0RpcUoyaWtUcm9WQWc9PSIsImRldmljZVNpZ25hdHVyZSI6IlQvbkZGRFlOK2FmK0JEa2xTTUQwU1QwTG0xZUxrVnN6ZTdzQjUrYkZORVNhVkFRVytSSXk5OEQzQ1JyTExFUGlFbjZBbm51aTZ5bDlFVTQ4ZUtCTGdRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM3NjU5MjYyNjUzOjFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUUJHR3l2UGwvazlvd1JpWk9ScVVTZkxTelhXbUpLVTVvZzlkT3dqR0N4RSJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMzU3NzcxOCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNL2kifQ==
  process.env.SESSION_ID |eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkkvQkV0cVI0bHpVZ2Jmc01PSHNKVUMzL00zbjhydzJxWGpyc3NXblBrRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUnYyN3NuYjQrcFBIUlNkSnFDTUhsWGhTOUlKNGhuWVlmeWc4RFlOa21Cdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDTG1SQTB3QWpic2c1bzF1TmFJcDZYZXVsSytKay9pNjVZSzMxd0JwT1dJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvZDA4cU5zeTFMdWREMURPNHpBdW54WlFvUmtkampNajFORFpTend1R2hvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9LZFcyVDR5QjRUNUtBT0VwY0xIOUJnVXU3ZFdHNlI5WWF4bjdVY2VUbU09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9ENUhJUjNLaUhQbVlObUNKOUpDZXFRaSsrRmhBU01yeTRUY3MybXUxMVE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0xiVUlMMkMvbGF2a1NPTlF6c21qTFBWcU9peElQcDJoa3dlcUNkbnUwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSlRPeEtabTFwNzJaazBUd0ZPRytzY1N4Vyt1OThxM2FqNDJLekVHSkYwYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjgzTmFkTThyZDdNMDZNWjlTMEdveDF2eG5tQ3hjZG55V1MyK2pTNlZhMGp3c1k5eGhINklCUlUwNDZubkJqSHZKRkNOUlFPWkRTMnF4WW5JRzdCSGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MSwiYWR2U2VjcmV0S2V5IjoiaWtuajZiT0k4YTlqUldiWjYwNUdob0xSVEhSV3I4d0MxWlhrS1NNQlVvOD0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMkhoWlVIQ2xTb20yamxxejBhUWNJUSIsInBob25lSWQiOiI4MThkZjNjZS04MDMzLTRjNzgtOTZiYi1mOWMwZWM2YWRlNjciLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiajNzeXNaT01DS2E3b2YveXNGK3lnaWkyOUlVPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IiswcVdmMXhNU3Vxd0lCbFZ3M3EwZ1dqTzJMQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJQOEJSRTFFWCIsIm1lIjp7ImlkIjoiMjM3NjU5MjYyNjUzOjFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2QgfCdkKXwnZCA8J2QgvCdkIog8J2QivCdkIjwnZCN8J2QhiDwnZCL8J2QhPCdkI7wnZCN8J2QiPCdkIPwnZCA8J2QkiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUFhxeFU4UTUrcnV0UVlZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQUVZYks4K1grVDJqQkdKazVHcFJKOHRMTmRhWWtwVG1pRDEwN0NNWUxFUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoibkxpVFFaeHc0ajJIODc0K0VLdFlDOFgxS1Uzd1dDQWQ3V3hBNm05ZjY5emxnZE1HeUtyMWdmZ3dvaGZMUkFXV2pTVmhsM05Rd0RpcUoyaWtUcm9WQWc9PSIsImRldmljZVNpZ25hdHVyZSI6IlQvbkZGRFlOK2FmK0JEa2xTTUQwU1QwTG0xZUxrVnN6ZTdzQjUrYkZORVNhVkFRVytSSXk5OEQzQ1JyTExFUGlFbjZBbm51aTZ5bDlFVTQ4ZUtCTGdRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM3NjU5MjYyNjUzOjFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUUJHR3l2UGwvazlvd1JpWk9ScVVTZkxTelhXbUpLVTVvZzlkT3dqR0N4RSJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMzU3NzcxOCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNL2kifQ==|
  "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkkvQkV0cVI0bHpVZ2Jmc01PSHNKVUMzL00zbjhydzJxWGpyc3NXblBrRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUnYyN3NuYjQrcFBIUlNkSnFDTUhsWGhTOUlKNGhuWVlmeWc4RFlOa21Cdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDTG1SQTB3QWpic2c1bzF1TmFJcDZYZXVsSytKay9pNjVZSzMxd0JwT1dJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvZDA4cU5zeTFMdWREMURPNHpBdW54WlFvUmtkampNajFORFpTend1R2hvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9LZFcyVDR5QjRUNUtBT0VwY0xIOUJnVXU3ZFdHNlI5WWF4bjdVY2VUbU09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9ENUhJUjNLaUhQbVlObUNKOUpDZXFRaSsrRmhBU01yeTRUY3MybXUxMVE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0xiVUlMMkMvbGF2a1NPTlF6c21qTFBWcU9peElQcDJoa3dlcUNkbnUwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSlRPeEtabTFwNzJaazBUd0ZPRytzY1N4Vyt1OThxM2FqNDJLekVHSkYwYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjgzTmFkTThyZDdNMDZNWjlTMEdveDF2eG5tQ3hjZG55V1MyK2pTNlZhMGp3c1k5eGhINklCUlUwNDZubkJqSHZKRkNOUlFPWkRTMnF4WW5JRzdCSGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MSwiYWR2U2VjcmV0S2V5IjoiaWtuajZiT0k4YTlqUldiWjYwNUdob0xSVEhSV3I4d0MxWlhrS1NNQlVvOD0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMkhoWlVIQ2xTb20yamxxejBhUWNJUSIsInBob25lSWQiOiI4MThkZjNjZS04MDMzLTRjNzgtOTZiYi1mOWMwZWM2YWRlNjciLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiajNzeXNaT01DS2E3b2YveXNGK3lnaWkyOUlVPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IiswcVdmMXhNU3Vxd0lCbFZ3M3EwZ1dqTzJMQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJQOEJSRTFFWCIsIm1lIjp7ImlkIjoiMjM3NjU5MjYyNjUzOjFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2QgfCdkKXwnZCA8J2QgvCdkIog8J2QivCdkIjwnZCN8J2QhiDwnZCL8J2QhPCdkI7wnZCN8J2QiPCdkIPwnZCA8J2QkiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUFhxeFU4UTUrcnV0UVlZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQUVZYks4K1grVDJqQkdKazVHcFJKOHRMTmRhWWtwVG1pRDEwN0NNWUxFUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoibkxpVFFaeHc0ajJIODc0K0VLdFlDOFgxS1Uzd1dDQWQ3V3hBNm05ZjY5emxnZE1HeUtyMWdmZ3dvaGZMUkFXV2pTVmhsM05Rd0RpcUoyaWtUcm9WQWc9PSIsImRldmljZVNpZ25hdHVyZSI6IlQvbkZGRFlOK2FmK0JEa2xTTUQwU1QwTG0xZUxrVnN6ZTdzQjUrYkZORVNhVkFRVytSSXk5OEQzQ1JyTExFUGlFbjZBbm51aTZ5bDlFVTQ4ZUtCTGdRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM3NjU5MjYyNjUzOjFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUUJHR3l2UGwvazlvd1JpWk9ScVVTZkxTelhXbUpLVTVvZzlkT3dqR0N4RSJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMzU3NzcxOCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNL2kifQ=="
module.exports = {
  menu: process.env.MENU || "1",
  HANDLERS: process.env.PREFIX || ".",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.0.0",
  caption: process.env.CAPTION || "`BRAND PRODUCT OF ☞⌜ KG TECH⌝☜`",
  author: process.env.PACK_AUTHER || "𝐁𝐥𝐀𝐂𝐊 𝐊𝐈𝐍𝐆 𝐋𝐄𝐎𝐍𝐈𝐃𝐀𝐒",
  packname: process.env.PACK_NAME || "𝐁𝐥𝐀𝐂𝐊 𝐊𝐈𝐍𝐆 𝐋𝐄𝐎𝐍𝐈𝐃𝐀𝐒",
  botname: process.env.BOT_NAME || "*𝐁𝐥𝐀𝐂𝐊 𝐊𝐈𝐍𝐆 𝐋𝐄𝐎𝐍𝐈𝐃𝐀𝐒",
  ownername: process.env.OWNER_NAME || "𝐁𝐥𝐀𝐂𝐊 𝐊𝐈𝐍𝐆 𝐋𝐄𝐎𝐍𝐈𝐃𝐀𝐒",
  errorChat: process.env.ERROR_CHAT || "",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "tCxobE1FqJgfbDZgsYQNHBFB",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "",
  antilink_values: process.env.ANTILINK_VALUES || "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "...d336",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "private",
  LANG: (process.env.THEME || "Kerm-md-v2").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
